version: "3.8"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  backend:
    image: the_martini_backend
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '5000:5000'
    volumes:
      - /app/backend/node_modules
      - ./backend:/app/backend
    depends_on:
      - nginx
      - dbmysql
  dbmysql:
    restart: always
    image: 'mysql:5.7'
    # entrypoint: sh -c "
    #     echo 'CREATE DATABASE IF NOT EXISTS the_martini; CREATE DATABASE IF NOT EXISTS the_martini_test;' > /docker-entrypoint-initdb.d/init.sql;/usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    ports:
      - '3306:3306'
    volumes:
      - /home/aninda/Development/node/the-martini/mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=the_martini
      - MYSQL_USER=martini
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret  